/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentation;

import DTO.AccCustDTO;
import bll.AccountServices;
import bll.CustomerServices;
import common.InputMoneyTranfer;
import common.checkMoney;
import entity.Account;
import entity.Card;
import entity.Customer;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author HUY-PC
 */
public class MoneyTranfer extends javax.swing.JFrame {

    /**
     * Creates new form ValidateCard
     */
    private String markPanel="pnlTransferID";
    
    //lưu String ID Receiver ở Panel Tranfer Info
    private StringBuilder strIDAccReceiver= new StringBuilder();
    
    //Lưu lượng tiền gửi ở Panel Amount
    private StringBuilder strAmount= new StringBuilder();
    
    //Định dạng tiền
    DecimalFormat formatter = new DecimalFormat("#,###");
    
    //Thẻ người gửi tiền
    private Card cardSource= bll.CardServices.getByCardNo("123456780");
    
    //Account người gửi tiền
    Account accSource= cardSource.getAccountID();
    
    //Account người nhận tiền
    private Account accReceiver=null;
    
    //Số tiền để duy trì tài khoản
    private int moneyBase= 50000;
    //Số tiền nhập để gửi
    private long money = 0;
    
    public MoneyTranfer(){
        initComponents();
//        timer = new Timer(3000, new ActionListener() {
//            @Override
//            public void actionPerformed(ActionEvent ae) {
//                pnlSub22.removeAll();
//                pnlSub22.add(Receiveinfo);
//                pnlSub22.repaint();
//                pnlSub22.validate();
//            }
//        });
//        timer.setRepeats(false);
//        timer.start();
//        pnlSub22.removeAll();
//        pnlSub22.add(pnlCashTranInfo);
//        pnlSub22.repaint();
//        pnlSub22.validate();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlPanel2 = new javax.swing.JPanel();
        pnlSub21 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lblBankName = new javax.swing.JLabel();
        lblWelcom = new javax.swing.JLabel();
        pnlSub22 = new javax.swing.JPanel();
        pnlTransferID = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblIDReceiver = new javax.swing.JLabel();
        lblAuthen10 = new javax.swing.JLabel();
        lblAuthen11 = new javax.swing.JLabel();
        lblPressEnter = new javax.swing.JLabel();
        txfInputID = new javax.swing.JTextField();
        pnlReceiveInfo = new javax.swing.JPanel();
        lblAuthen13 = new javax.swing.JLabel();
        lblTitleReceiver = new javax.swing.JLabel();
        lblAuthen15 = new javax.swing.JLabel();
        lblAuthen16 = new javax.swing.JLabel();
        lblOutputName = new javax.swing.JLabel();
        lblOutputID = new javax.swing.JLabel();
        pnlAmount = new javax.swing.JPanel();
        lblAuthen17 = new javax.swing.JLabel();
        lblAuthen18 = new javax.swing.JLabel();
        lblAuthen19 = new javax.swing.JLabel();
        txfAmount = new javax.swing.JTextField();
        pnlCashTranInfo = new javax.swing.JPanel();
        lblAuthen20 = new javax.swing.JLabel();
        lblTitleCashTranInfo = new javax.swing.JLabel();
        lblAuthen22 = new javax.swing.JLabel();
        lblAuthen23 = new javax.swing.JLabel();
        lblAuthen24 = new javax.swing.JLabel();
        lblNameInCashTran = new javax.swing.JLabel();
        lblIDInCashTran = new javax.swing.JLabel();
        lblAmountInCashTran = new javax.swing.JLabel();
        pnlSuccess = new javax.swing.JPanel();
        lblAuthen28 = new javax.swing.JLabel();
        lblAuthen30 = new javax.swing.JLabel();
        lblAuthen25 = new javax.swing.JLabel();
        pnlFailAcc = new javax.swing.JPanel();
        lblAuthen29 = new javax.swing.JLabel();
        lblAuthen31 = new javax.swing.JLabel();
        lblAuthen26 = new javax.swing.JLabel();
        pnlFailMoney = new javax.swing.JPanel();
        lblAuthen32 = new javax.swing.JLabel();
        lblAuthen33 = new javax.swing.JLabel();
        lblAuthen27 = new javax.swing.JLabel();
        pnlPanel4 = new javax.swing.JPanel();
        pnlPanel3 = new javax.swing.JPanel();
        jBtn1 = new javax.swing.JButton();
        jBtn2 = new javax.swing.JButton();
        jBtn3 = new javax.swing.JButton();
        jBtn4 = new javax.swing.JButton();
        jBtn5 = new javax.swing.JButton();
        jBtn9 = new javax.swing.JButton();
        jBtn6 = new javax.swing.JButton();
        jBtn7 = new javax.swing.JButton();
        jBtn8 = new javax.swing.JButton();
        jBtn10 = new javax.swing.JButton();
        jBtn11 = new javax.swing.JButton();
        jBtn12 = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnEnter = new javax.swing.JButton();
        pnlButton123 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnlButton456 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPanel1.setPreferredSize(new java.awt.Dimension(800, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CHUYỂN TIỀN");

        javax.swing.GroupLayout pnlPanel1Layout = new javax.swing.GroupLayout(pnlPanel1);
        pnlPanel1.setLayout(pnlPanel1Layout);
        pnlPanel1Layout.setHorizontalGroup(
            pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        pnlPanel1Layout.setVerticalGroup(
            pnlPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        pnlPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        pnlPanel2.setPreferredSize(new java.awt.Dimension(450, 450));

        pnlSub21.setPreferredSize(new java.awt.Dimension(80, 80));

        logo.setText("LOGO");
        logo.setPreferredSize(new java.awt.Dimension(58, 14));

        lblBankName.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        lblBankName.setText("WORLD BANK");

        lblWelcom.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        lblWelcom.setText("Xin kính chào quý khách !");

        javax.swing.GroupLayout pnlSub21Layout = new javax.swing.GroupLayout(pnlSub21);
        pnlSub21.setLayout(pnlSub21Layout);
        pnlSub21Layout.setHorizontalGroup(
            pnlSub21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSub21Layout.createSequentialGroup()
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(pnlSub21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblWelcom)
                    .addComponent(lblBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75))
        );
        pnlSub21Layout.setVerticalGroup(
            pnlSub21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSub21Layout.createSequentialGroup()
                .addGroup(pnlSub21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlSub21Layout.createSequentialGroup()
                        .addComponent(lblBankName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblWelcom))
                    .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pnlSub22.setPreferredSize(new java.awt.Dimension(183, 350));
        pnlSub22.setLayout(new java.awt.CardLayout());

        lblTitle.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblTitle.setText("Nhập số tài khoản bạn muốn chuyển tiền");

        lblIDReceiver.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblIDReceiver.setText("ID người nhận:");

        lblAuthen10.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthen10.setText("Tên người gửi:");

        lblAuthen11.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthen11.setText("ID người gửi:");

        lblPressEnter.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblPressEnter.setText("Ấn Enter để tiếp tục, Cancel để hủy");

        txfInputID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfInputIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlTransferIDLayout = new javax.swing.GroupLayout(pnlTransferID);
        pnlTransferID.setLayout(pnlTransferIDLayout);
        pnlTransferIDLayout.setHorizontalGroup(
            pnlTransferIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransferIDLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(pnlTransferIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTransferIDLayout.createSequentialGroup()
                        .addComponent(lblAuthen11, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlTransferIDLayout.createSequentialGroup()
                        .addGroup(pnlTransferIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAuthen10)
                            .addGroup(pnlTransferIDLayout.createSequentialGroup()
                                .addComponent(lblIDReceiver)
                                .addGap(54, 54, 54)
                                .addComponent(txfInputID, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(pnlTransferIDLayout.createSequentialGroup()
                .addGroup(pnlTransferIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlTransferIDLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(lblPressEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlTransferIDLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblTitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlTransferIDLayout.setVerticalGroup(
            pnlTransferIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTransferIDLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(lblAuthen10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(lblAuthen11, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlTransferIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfInputID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(lblPressEnter, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pnlSub22.add(pnlTransferID, "card3");

        pnlReceiveInfo.setPreferredSize(new java.awt.Dimension(350, 350));

        lblAuthen13.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAuthen13.setText("Ấn Enter để tiếp tục, Cancel để quay lại");

        lblTitleReceiver.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblTitleReceiver.setText("Thông tin người nhận");

        lblAuthen15.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthen15.setText("ID tài khoản nhận:");

        lblAuthen16.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthen16.setText("Tên tài khoản người nhận:");

        lblOutputName.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblOutputID.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnlReceiveInfoLayout = new javax.swing.GroupLayout(pnlReceiveInfo);
        pnlReceiveInfo.setLayout(pnlReceiveInfoLayout);
        pnlReceiveInfoLayout.setHorizontalGroup(
            pnlReceiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReceiveInfoLayout.createSequentialGroup()
                .addGroup(pnlReceiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlReceiveInfoLayout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(lblTitleReceiver))
                    .addGroup(pnlReceiveInfoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlReceiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAuthen16)
                            .addComponent(lblAuthen15))
                        .addGap(18, 18, 18)
                        .addGroup(pnlReceiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblOutputName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblOutputID, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)))
                    .addGroup(pnlReceiveInfoLayout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(lblAuthen13, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        pnlReceiveInfoLayout.setVerticalGroup(
            pnlReceiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlReceiveInfoLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(lblTitleReceiver, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(pnlReceiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthen16, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOutputName))
                .addGap(18, 18, 18)
                .addGroup(pnlReceiveInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthen15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOutputID))
                .addGap(32, 32, 32)
                .addComponent(lblAuthen13, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        pnlSub22.add(pnlReceiveInfo, "card2");

        lblAuthen17.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblAuthen17.setText("Ấn Enter để tiếp tục, Cancel để hủy");

        lblAuthen18.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        lblAuthen18.setText("Thông tin số tiền");

        lblAuthen19.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthen19.setText("Amount:");

        javax.swing.GroupLayout pnlAmountLayout = new javax.swing.GroupLayout(pnlAmount);
        pnlAmount.setLayout(pnlAmountLayout);
        pnlAmountLayout.setHorizontalGroup(
            pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAmountLayout.createSequentialGroup()
                .addGroup(pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAmountLayout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(lblAuthen17, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlAmountLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(lblAuthen19)
                        .addGap(28, 28, 28)
                        .addGroup(pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAuthen18, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlAmountLayout.setVerticalGroup(
            pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAmountLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lblAuthen18, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(pnlAmountLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthen19, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAuthen17, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        pnlSub22.add(pnlAmount, "card4");

        pnlCashTranInfo.setPreferredSize(new java.awt.Dimension(350, 350));

        lblAuthen20.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lblAuthen20.setText("Ấn Enter để chuyển tiền, Cancel để hủy");

        lblTitleCashTranInfo.setFont(new java.awt.Font("Tahoma", 0, 19)); // NOI18N
        lblTitleCashTranInfo.setText("Thông tin giao dịch");

        lblAuthen22.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthen22.setText("Số tiền:");

        lblAuthen23.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthen23.setText("Tên tài khoản nhận:");

        lblAuthen24.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        lblAuthen24.setText("ID tài khoản nhận:");

        lblNameInCashTran.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblIDInCashTran.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        lblAmountInCashTran.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N

        javax.swing.GroupLayout pnlCashTranInfoLayout = new javax.swing.GroupLayout(pnlCashTranInfo);
        pnlCashTranInfo.setLayout(pnlCashTranInfoLayout);
        pnlCashTranInfoLayout.setHorizontalGroup(
            pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCashTranInfoLayout.createSequentialGroup()
                .addGroup(pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCashTranInfoLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCashTranInfoLayout.createSequentialGroup()
                                .addComponent(lblAuthen23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblNameInCashTran, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlCashTranInfoLayout.createSequentialGroup()
                                .addGroup(pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAuthen24)
                                    .addComponent(lblAuthen22))
                                .addGap(18, 18, 18)
                                .addGroup(pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAmountInCashTran, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIDInCashTran, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnlCashTranInfoLayout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(lblTitleCashTranInfo))
                    .addGroup(pnlCashTranInfoLayout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(lblAuthen20, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnlCashTranInfoLayout.setVerticalGroup(
            pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCashTranInfoLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitleCashTranInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthen23, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameInCashTran))
                .addGap(27, 27, 27)
                .addGroup(pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthen24)
                    .addComponent(lblIDInCashTran))
                .addGap(27, 27, 27)
                .addGroup(pnlCashTranInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAuthen22, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmountInCashTran))
                .addGap(38, 38, 38)
                .addComponent(lblAuthen20, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pnlSub22.add(pnlCashTranInfo, "card2");

        pnlSuccess.setPreferredSize(new java.awt.Dimension(350, 350));

        lblAuthen28.setBackground(new java.awt.Color(51, 51, 255));
        lblAuthen28.setFont(new java.awt.Font("Tahoma", 0, 32)); // NOI18N
        lblAuthen28.setText("Chuyển tiền thành công!");

        lblAuthen30.setBackground(new java.awt.Color(0, 0, 0));
        lblAuthen30.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAuthen30.setText("Bạn có muốn tiếp tục chuyển tiền không?");

        lblAuthen25.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblAuthen25.setText("Ấn Enter để tiếp tục, Cancel để hủy");

        javax.swing.GroupLayout pnlSuccessLayout = new javax.swing.GroupLayout(pnlSuccess);
        pnlSuccess.setLayout(pnlSuccessLayout);
        pnlSuccessLayout.setHorizontalGroup(
            pnlSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuccessLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblAuthen25, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuccessLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuccessLayout.createSequentialGroup()
                        .addComponent(lblAuthen28)
                        .addGap(39, 39, 39))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuccessLayout.createSequentialGroup()
                        .addComponent(lblAuthen30)
                        .addGap(50, 50, 50))))
        );
        pnlSuccessLayout.setVerticalGroup(
            pnlSuccessLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuccessLayout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(lblAuthen28, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblAuthen30, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblAuthen25, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        pnlSub22.add(pnlSuccess, "card2");

        pnlFailAcc.setPreferredSize(new java.awt.Dimension(350, 350));

        lblAuthen29.setBackground(new java.awt.Color(51, 51, 255));
        lblAuthen29.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAuthen29.setText("Không xác định được người nhận");

        lblAuthen31.setBackground(new java.awt.Color(0, 0, 0));
        lblAuthen31.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAuthen31.setText("Bạn có muốn tiếp tục chuyển tiền không?");

        lblAuthen26.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblAuthen26.setText("Ấn Enter để tiếp tục, Cancel để hủy");

        javax.swing.GroupLayout pnlFailAccLayout = new javax.swing.GroupLayout(pnlFailAcc);
        pnlFailAcc.setLayout(pnlFailAccLayout);
        pnlFailAccLayout.setHorizontalGroup(
            pnlFailAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFailAccLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblAuthen31)
                .addGap(50, 50, 50))
            .addGroup(pnlFailAccLayout.createSequentialGroup()
                .addGroup(pnlFailAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlFailAccLayout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(lblAuthen26, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlFailAccLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblAuthen29)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlFailAccLayout.setVerticalGroup(
            pnlFailAccLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFailAccLayout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addComponent(lblAuthen29, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(lblAuthen31, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblAuthen26, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        pnlSub22.add(pnlFailAcc, "card2");

        pnlFailMoney.setPreferredSize(new java.awt.Dimension(350, 350));

        lblAuthen32.setBackground(new java.awt.Color(51, 51, 255));
        lblAuthen32.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblAuthen32.setText("Tài khoản của bạn không đủ tiền!");

        lblAuthen33.setBackground(new java.awt.Color(0, 0, 0));
        lblAuthen33.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblAuthen33.setText("Bạn có muốn tiếp tục chuyển tiền không?");

        lblAuthen27.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        lblAuthen27.setText("Ấn Enter để tiếp tục, Cancel để hủy");

        javax.swing.GroupLayout pnlFailMoneyLayout = new javax.swing.GroupLayout(pnlFailMoney);
        pnlFailMoney.setLayout(pnlFailMoneyLayout);
        pnlFailMoneyLayout.setHorizontalGroup(
            pnlFailMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFailMoneyLayout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(lblAuthen27, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFailMoneyLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlFailMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFailMoneyLayout.createSequentialGroup()
                        .addComponent(lblAuthen33)
                        .addGap(50, 50, 50))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFailMoneyLayout.createSequentialGroup()
                        .addComponent(lblAuthen32)
                        .addGap(34, 34, 34))))
        );
        pnlFailMoneyLayout.setVerticalGroup(
            pnlFailMoneyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlFailMoneyLayout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addComponent(lblAuthen32, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lblAuthen33, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(lblAuthen27, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121))
        );

        pnlSub22.add(pnlFailMoney, "card2");

        javax.swing.GroupLayout pnlPanel2Layout = new javax.swing.GroupLayout(pnlPanel2);
        pnlPanel2.setLayout(pnlPanel2Layout);
        pnlPanel2Layout.setHorizontalGroup(
            pnlPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanel2Layout.createSequentialGroup()
                .addComponent(pnlSub22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlSub21, javax.swing.GroupLayout.DEFAULT_SIZE, 446, Short.MAX_VALUE)
        );
        pnlPanel2Layout.setVerticalGroup(
            pnlPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanel2Layout.createSequentialGroup()
                .addComponent(pnlSub21, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlSub22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pnlPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnlPanel4.setPreferredSize(new java.awt.Dimension(800, 25));

        javax.swing.GroupLayout pnlPanel4Layout = new javax.swing.GroupLayout(pnlPanel4);
        pnlPanel4.setLayout(pnlPanel4Layout);
        pnlPanel4Layout.setHorizontalGroup(
            pnlPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 798, Short.MAX_VALUE)
        );
        pnlPanel4Layout.setVerticalGroup(
            pnlPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 23, Short.MAX_VALUE)
        );

        jBtn1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn1.setText("1");
        jBtn1.setBorder(null);
        jBtn1.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn1ActionPerformed(evt);
            }
        });

        jBtn2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn2.setText("2");
        jBtn2.setBorder(null);
        jBtn2.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn2ActionPerformed(evt);
            }
        });

        jBtn3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn3.setText("3");
        jBtn3.setBorder(null);
        jBtn3.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn3ActionPerformed(evt);
            }
        });

        jBtn4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn4.setText("4");
        jBtn4.setBorder(null);
        jBtn4.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn4ActionPerformed(evt);
            }
        });

        jBtn5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn5.setText("5");
        jBtn5.setBorder(null);
        jBtn5.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn5ActionPerformed(evt);
            }
        });

        jBtn9.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn9.setText("9");
        jBtn9.setBorder(null);
        jBtn9.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn9ActionPerformed(evt);
            }
        });

        jBtn6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn6.setText("6");
        jBtn6.setBorder(null);
        jBtn6.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn6ActionPerformed(evt);
            }
        });

        jBtn7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn7.setText("7");
        jBtn7.setBorder(null);
        jBtn7.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn7ActionPerformed(evt);
            }
        });

        jBtn8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn8.setText("8");
        jBtn8.setBorder(null);
        jBtn8.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn8ActionPerformed(evt);
            }
        });

        jBtn10.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn10.setText("0");
        jBtn10.setBorder(null);
        jBtn10.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn10ActionPerformed(evt);
            }
        });

        jBtn11.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn11.setText(".");
        jBtn11.setBorder(null);
        jBtn11.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn11ActionPerformed(evt);
            }
        });

        jBtn12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jBtn12.setBorder(null);
        jBtn12.setPreferredSize(new java.awt.Dimension(40, 40));
        jBtn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn12ActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnCancel.setText("CANCEL");
        btnCancel.setBorder(null);
        btnCancel.setPreferredSize(new java.awt.Dimension(80, 40));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.setBorder(null);
        btnClear.setPreferredSize(new java.awt.Dimension(80, 40));
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnEnter.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnEnter.setText("ENTER");
        btnEnter.setBorder(null);
        btnEnter.setPreferredSize(new java.awt.Dimension(80, 40));
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlPanel3Layout = new javax.swing.GroupLayout(pnlPanel3);
        pnlPanel3.setLayout(pnlPanel3Layout);
        pnlPanel3Layout.setHorizontalGroup(
            pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanel3Layout.createSequentialGroup()
                        .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlPanel3Layout.createSequentialGroup()
                                .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlPanel3Layout.createSequentialGroup()
                                .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jBtn10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlPanel3Layout.createSequentialGroup()
                                        .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(pnlPanel3Layout.createSequentialGroup()
                                        .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jBtn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(76, Short.MAX_VALUE))
        );
        pnlPanel3Layout.setVerticalGroup(
            pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPanel3Layout.createSequentialGroup()
                .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlPanel3Layout.createSequentialGroup()
                        .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtn7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtn9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEnter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtn12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtn10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtn11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("Button1");
        jButton1.setPreferredSize(new java.awt.Dimension(115, 47));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Button2");
        jButton2.setPreferredSize(new java.awt.Dimension(115, 47));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Button3");
        jButton3.setPreferredSize(new java.awt.Dimension(115, 47));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButton123Layout = new javax.swing.GroupLayout(pnlButton123);
        pnlButton123.setLayout(pnlButton123Layout);
        pnlButton123Layout.setHorizontalGroup(
            pnlButton123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButton123Layout.createSequentialGroup()
                .addGap(0, 20, Short.MAX_VALUE)
                .addGroup(pnlButton123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        pnlButton123Layout.setVerticalGroup(
            pnlButton123Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButton123Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        pnlButton456.setPreferredSize(new java.awt.Dimension(135, 260));

        jButton4.setText("Button4");
        jButton4.setPreferredSize(new java.awt.Dimension(115, 47));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton6.setText("Button6");
        jButton6.setPreferredSize(new java.awt.Dimension(115, 47));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton5.setText("Button5");
        jButton5.setPreferredSize(new java.awt.Dimension(115, 47));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlButton456Layout = new javax.swing.GroupLayout(pnlButton456);
        pnlButton456.setLayout(pnlButton456Layout);
        pnlButton456Layout.setHorizontalGroup(
            pnlButton456Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlButton456Layout.createSequentialGroup()
                .addGroup(pnlButton456Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        pnlButton456Layout.setVerticalGroup(
            pnlButton456Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlButton456Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(pnlButton123, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnlPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnlButton456, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(pnlPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(pnlPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pnlPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(143, 143, 143)
                                .addComponent(pnlButton456, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(pnlButton123, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pnlPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn1ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn1.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn1.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn1ActionPerformed

    private void jBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn2ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn2.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn2.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn2ActionPerformed

    private void jBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn3ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn3.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn3.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn3ActionPerformed

    private void jBtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn4ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn4.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn4.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn4ActionPerformed

    private void jBtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn5ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn5.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn5.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn5ActionPerformed

    private void jBtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn9ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn9.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn9.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn9ActionPerformed

    private void jBtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn6ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn6.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn6.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn6ActionPerformed

    private void jBtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn7ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn7.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn7.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn7ActionPerformed

    private void jBtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn8ActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn8.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn8.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn8ActionPerformed

    private void jBtn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn10ActionPerformed
        jBtn10.setText("0");
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.append(jBtn10.getText());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else{
            if(markPanel.equals("pnlAmount")){
                strAmount.append(jBtn10.getText());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_jBtn10ActionPerformed

    private void jBtn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn11ActionPerformed

    private void jBtn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtn12ActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        if(markPanel.equals("pnlTransferID"))
        {
            JOptionPane.showMessageDialog(null, "Quay về màn hình chính");
            pnlSub22.removeAll();
            pnlSub22.add(pnlTransferID);
            pnlSub22.repaint();
            pnlSub22.validate();
            markPanel="pnlTransferID";
        }
        else if(markPanel.equals("pnlAmount"))
        {
            JOptionPane.showMessageDialog(null, "Quay về màn hình chính");
            pnlSub22.removeAll();
            pnlSub22.add(pnlTransferID);
            pnlSub22.repaint();
            pnlSub22.validate();
            markPanel="pnlTransferID";
        }
        else if(markPanel.equals("pnlReceiveInfo"))
        {
            pnlSub22.removeAll();
            pnlSub22.add(pnlTransferID);
            pnlSub22.repaint();
            pnlSub22.validate();
            markPanel="pnlTransferID";
        }
        else if(markPanel.equals("pnlCashTranInfo"))
        {
            JOptionPane.showMessageDialog(null, "Quay về màn hình chính");
            pnlSub22.removeAll();
            pnlSub22.add(pnlTransferID);
            pnlSub22.repaint();
            pnlSub22.validate();
            markPanel="pnlTransferID";
        }
        else if(markPanel.equals("pnlSuccess"))
        {
            JOptionPane.showMessageDialog(null, "Quay về màn hình chính");
            pnlSub22.removeAll();
            pnlSub22.add(pnlTransferID);
            pnlSub22.repaint();
            pnlSub22.validate();
            markPanel="pnlTransferID";
        }
        else if(markPanel.equals("pnlFailAcc"))
        {
            JOptionPane.showMessageDialog(null, "Quay về màn hình chính");
            pnlSub22.removeAll();
            pnlSub22.add(pnlTransferID);
            pnlSub22.repaint();
            pnlSub22.validate();
            markPanel="pnlTransferID";
        }
        else if(markPanel.equals("pnlFailMoney"))
        {
            JOptionPane.showMessageDialog(null, "Quay về màn hình chính");
            pnlSub22.removeAll();
            pnlSub22.add(pnlTransferID);
            pnlSub22.repaint();
            pnlSub22.validate();
            markPanel="pnlTransferID";
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        if(markPanel.equals("pnlTransferID")){
            strIDAccReceiver.delete(0, strIDAccReceiver.length());
            InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
            txfInputID.requestFocus();
        }
        else 
        {
            if(markPanel.equals("pnlAmount"))
            {
                strAmount.delete(0, strAmount.length());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                txfAmount.requestFocus();
            }
        }
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        
        if(markPanel.equals("pnlTransferID")){
            accReceiver= AccountServices.getByAccountID(strIDAccReceiver.toString());
//            System.out.println("ID acc Receiver: "+accReceiver+ "--- "+ cardSource.getAccountID());
            if(accReceiver == null || (accReceiver.getAccountID() == cardSource.getAccountID().getAccountID())){
                pnlSub22.removeAll();
                pnlSub22.add(pnlFailAcc);
                pnlSub22.repaint();
                pnlSub22.validate();
                markPanel="pnlFailAcc";
            }
            else
            {
                pnlSub22.removeAll();
                pnlSub22.add(pnlReceiveInfo);
                pnlSub22.repaint();
                pnlSub22.validate();
                markPanel="pnlReceiveInfo";
                
                //Đổ dữ liệu vào panel ReceiverInfo
                AccCustDTO accountCustomDTO= CustomerServices.getNameByAccID(Integer.parseInt(strIDAccReceiver.toString()));
                lblOutputName.setText(accountCustomDTO.getName());
                lblOutputID.setText(""+accountCustomDTO.getAccountID());
            }
        }
        else
        {
            if(markPanel.equals("pnlReceiveInfo"))
            {
                pnlSub22.removeAll();
                pnlSub22.add(pnlAmount);
                pnlSub22.repaint();
                pnlSub22.validate();
                markPanel="pnlAmount";
            }
            else if(markPanel.equals("pnlAmount"))
            {
                if(!strAmount.toString().equals(""))
                {
                    money= Integer.parseInt(strAmount.toString());
                    System.out.println("Money trong pnlAmount: "+money);
                    if(accSource.getBalance() >= moneyBase+ money) //Số tiền min trong TK = moneyBase
                    {
                        if(checkMoney.ktrTienGui(money)){
                            pnlSub22.removeAll();
                            pnlSub22.add(pnlCashTranInfo);
                            pnlSub22.repaint();
                            pnlSub22.validate();
                            markPanel="pnlCashTranInfo";
                            
                            //Đổ dữ liệu vào panel pnlCashTranInfo
                            Customer custReceiver= accReceiver.getCustID();
                            lblNameInCashTran.setText(custReceiver.getName());
                            lblIDInCashTran.setText(""+accReceiver.getAccountID());
                            lblAmountInCashTran.setText(formatter.format(money) + " VNĐ");
                        }
                        else{
                            JOptionPane.showMessageDialog(null, "So tien ko chia het 50 000");
                        }
                    }
                    else{
                        pnlSub22.removeAll();
                        pnlSub22.add(pnlFailMoney);
                        pnlSub22.repaint();
                        pnlSub22.validate();
                        markPanel="pnlFailMoney";
                    }
                }
            }
            else if(markPanel.equals("pnlCashTranInfo")){
                accSource.setBalance( (accSource.getBalance()- money) );
                accReceiver.setBalance( (accReceiver.getBalance()+ money));
                
                if(bll.AccountServices.updateAccount(accSource) && bll.AccountServices.updateAccount(accReceiver)){
                    System.out.println("UPDATE thanh cong");
                }
                else
                    System.out.println("Khong thanh cong");
                pnlSub22.removeAll();
                pnlSub22.add(pnlSuccess);
                pnlSub22.repaint();
                pnlSub22.validate();
                markPanel="pnlSuccess";
                JOptionPane.showMessageDialog(null, "Ghi hóa đơn + ghi log");
            }
            else if(markPanel.equals("pnlSuccess"))
            {
                //Xóa text Field trong Nhập ID và Nhập tiền
                strIDAccReceiver.delete(0, strIDAccReceiver.length());
                InputMoneyTranfer.nhapIDAccReceiver(strIDAccReceiver.toString(), txfInputID);
                strAmount.delete(0, strAmount.length());
                InputMoneyTranfer.nhapAmount(strAmount.toString(), txfAmount);
                
                pnlSub22.removeAll();
                pnlSub22.add(pnlTransferID);
                pnlSub22.repaint();
                pnlSub22.validate();
                markPanel="pnlTransferID";
            }
            else if(markPanel.equals("pnlFailAcc"))
            {
                pnlSub22.removeAll();
                pnlSub22.add(pnlTransferID);
                pnlSub22.repaint();
                pnlSub22.validate();
                markPanel="pnlTransferID";
            }
            else if(markPanel.equals("pnlFailMoney"))
            {
                pnlSub22.removeAll();
                pnlSub22.add(pnlAmount);
                pnlSub22.repaint();
                pnlSub22.validate();
                markPanel="pnlAmount";
            }
            
        }
            
    }//GEN-LAST:event_btnEnterActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void txfInputIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfInputIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfInputIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MoneyTranfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MoneyTranfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MoneyTranfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MoneyTranfer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new MoneyTranfer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton jBtn1;
    private javax.swing.JButton jBtn10;
    private javax.swing.JButton jBtn11;
    private javax.swing.JButton jBtn12;
    private javax.swing.JButton jBtn2;
    private javax.swing.JButton jBtn3;
    private javax.swing.JButton jBtn4;
    private javax.swing.JButton jBtn5;
    private javax.swing.JButton jBtn6;
    private javax.swing.JButton jBtn7;
    private javax.swing.JButton jBtn8;
    private javax.swing.JButton jBtn9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAmountInCashTran;
    private javax.swing.JLabel lblAuthen10;
    private javax.swing.JLabel lblAuthen11;
    private javax.swing.JLabel lblAuthen13;
    private javax.swing.JLabel lblAuthen15;
    private javax.swing.JLabel lblAuthen16;
    private javax.swing.JLabel lblAuthen17;
    private javax.swing.JLabel lblAuthen18;
    private javax.swing.JLabel lblAuthen19;
    private javax.swing.JLabel lblAuthen20;
    private javax.swing.JLabel lblAuthen22;
    private javax.swing.JLabel lblAuthen23;
    private javax.swing.JLabel lblAuthen24;
    private javax.swing.JLabel lblAuthen25;
    private javax.swing.JLabel lblAuthen26;
    private javax.swing.JLabel lblAuthen27;
    private javax.swing.JLabel lblAuthen28;
    private javax.swing.JLabel lblAuthen29;
    private javax.swing.JLabel lblAuthen30;
    private javax.swing.JLabel lblAuthen31;
    private javax.swing.JLabel lblAuthen32;
    private javax.swing.JLabel lblAuthen33;
    private javax.swing.JLabel lblBankName;
    private javax.swing.JLabel lblIDInCashTran;
    private javax.swing.JLabel lblIDReceiver;
    private javax.swing.JLabel lblNameInCashTran;
    private javax.swing.JLabel lblOutputID;
    private javax.swing.JLabel lblOutputName;
    private javax.swing.JLabel lblPressEnter;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblTitleCashTranInfo;
    private javax.swing.JLabel lblTitleReceiver;
    private javax.swing.JLabel lblWelcom;
    private javax.swing.JLabel logo;
    private javax.swing.JPanel pnlAmount;
    private javax.swing.JPanel pnlButton123;
    private javax.swing.JPanel pnlButton456;
    private javax.swing.JPanel pnlCashTranInfo;
    private javax.swing.JPanel pnlFailAcc;
    private javax.swing.JPanel pnlFailMoney;
    private javax.swing.JPanel pnlPanel1;
    private javax.swing.JPanel pnlPanel2;
    private javax.swing.JPanel pnlPanel3;
    private javax.swing.JPanel pnlPanel4;
    private javax.swing.JPanel pnlReceiveInfo;
    private javax.swing.JPanel pnlSub21;
    private javax.swing.JPanel pnlSub22;
    private javax.swing.JPanel pnlSuccess;
    private javax.swing.JPanel pnlTransferID;
    private javax.swing.JTextField txfAmount;
    private javax.swing.JTextField txfInputID;
    // End of variables declaration//GEN-END:variables

}
